#!/usr/bin/env bash
function setupAtom() {
    # Keep it all alphabetically (but grouped) for easier changes  
    # 1. Install packages
    apm install atom-beautify
    apm install blade-snippets
    apm install color-picker
    apm install docblockr
    apm install imdone-atom
    apm install language-blade
    apm install language-dotfiles
    apm install linter
    apm install linter-eslint
    apm install linter-less
    apm install linter-php
    apm install linter-sass-lint
    apm install merge-conflicts
    apm install minimap
    apm install php-cs-fixer
    apm install pigments
    apm install react
    apm install travis-ci-status
    apm install wordpress-api

    # 2. Install Theme/s and co.
    apm install atom-material-ui
    apm install file-icons
    apm install zero-dark-matrix-syntax

    # 3. update config and styles file
    cd ~/.atom
    git clone https://github.com/lukasjuhas/dotfiles.git
    mv -v dotfiles/atom/config.cson ~/.atom
    mv -v dotfiles/atom/styles.less ~/.atom
    rm -rf dotfiles
}

setupAtom
