#!/usr/bin/env bash
function setupAtom() {

    # 1. Install packages
    apm install docblockr
    apm install pigments
    apm install minimap
    apm install color-picker
    apm install merge-conflicts
    apm install autoclose-html
    apm install linter
    apm install linter-eslint
    apm install linter-php
    apm install php-cs-fixer
    apm install atom-beautify
    apm install react
    apm install imdone-atom
    apm install language-blade
    apm install blade-snippets

    # 2. Install Theme/s
    apm install seti-ui
    apm install seti-syntax

    # 3. update config and styles file
    cd ~/.atom
    git clone https://github.com/lukasjuhas/dotfiles.git
    mv -v dotfiles/Atom/config.cson ~/.atom
    mv -v dotfiles/Atom/styles.less ~/.atom
    rm -rf dotfiles
}

setupAtom
